<?php

use Illuminate\Database\Seeder;
use App\CarModel;

class ModelTableSeeder extends Seeder {
    public function run()
    {
        DB::table('car_models')->delete();

        $models = [
            '1' => ['mark_id' => '1', 'title' => 'EL', 'slug' => 'el' ],
            '2' => ['mark_id' => '1', 'title' => 'Integra', 'slug' => 'integra' ],
            '3' => ['mark_id' => '1', 'title' => 'MDX', 'slug' => 'mdx' ],
            '4' => ['mark_id' => '1', 'title' => 'NSX', 'slug' => 'nsx' ],
            '5' => ['mark_id' => '1', 'title' => 'RDX', 'slug' => 'rdx' ],
            '6' => ['mark_id' => '1', 'title' => 'RSX', 'slug' => 'rsx' ],
            '7' => ['mark_id' => '1', 'title' => 'ZDX', 'slug' => 'zdx' ],

            '8' => ['mark_id' => '2', 'title' => 'Brera', 'slug' => 'brera' ],
            '9' => ['mark_id' => '2', 'title' => 'Giulietta', 'slug' => 'giulietta' ],
            '10' => ['mark_id' => '2', 'title' => 'GT', 'slug' => 'gt' ],
            '11' => ['mark_id' => '2', 'title' => 'Spider', 'slug' => 'spider' ],

            '12' => ['mark_id' => '3', 'title' => 'A1', 'slug' => 'a1' ],
            '13' => ['mark_id' => '3', 'title' => 'A2', 'slug' => 'a2' ],
            '14' => ['mark_id' => '3', 'title' => 'A3', 'slug' => 'a3' ],
            '15' => ['mark_id' => '3', 'title' => 'A4', 'slug' => 'a4' ],
            '16' => ['mark_id' => '3', 'title' => 'A5', 'slug' => 'a5' ],
            '17' => ['mark_id' => '3', 'title' => 'A6', 'slug' => 'a6' ],
            '18' => ['mark_id' => '3', 'title' => 'A7', 'slug' => 'a7' ],
            '19' => ['mark_id' => '3', 'title' => 'A8', 'slug' => 'a8' ],
            '20' => ['mark_id' => '3', 'title' => 'Q3', 'slug' => 'q3' ],
            '21' => ['mark_id' => '3', 'title' => 'Q5', 'slug' => 'q5' ],
            '22' => ['mark_id' => '3', 'title' => 'Q7', 'slug' => 'q7' ],
            '23' => ['mark_id' => '3', 'title' => 'R8', 'slug' => 'r8' ],
            '24' => ['mark_id' => '3', 'title' => 'S4', 'slug' => 's4' ],
            '25' => ['mark_id' => '3', 'title' => 'S5', 'slug' => 's5' ],
            '26' => ['mark_id' => '3', 'title' => 'S6', 'slug' => 's6' ],
            '28' => ['mark_id' => '3', 'title' => 'S7', 'slug' => 's7' ],
            '29' => ['mark_id' => '3', 'title' => 'S8', 'slug' => 's8' ],
            '30' => ['mark_id' => '3', 'title' => 'TT', 'slug' => 'tt' ],

            '31' => ['mark_id' => '4', 'title' => 'Arnage', 'slug' => 'arnage' ],
            '32' => ['mark_id' => '4', 'title' => 'Azure', 'slug' => 'azure' ],
            '33' => ['mark_id' => '4', 'title' => 'Brooklands', 'slug' => 'brooklands' ],
            '34' => ['mark_id' => '4', 'title' => 'Continental', 'slug' => 'continental' ],
            '35' => ['mark_id' => '4', 'title' => 'Mulsanne', 'slug' => 'mulsanne' ],

            '36' => ['mark_id' => '5', 'title' => '1 series', 'slug' => '1_series' ],
            '37' => ['mark_id' => '5', 'title' => '2 series', 'slug' => '2_series' ],
            '38' => ['mark_id' => '5', 'title' => '3 series', 'slug' => '3_series' ],
            '39' => ['mark_id' => '5', 'title' => '4 series', 'slug' => '4_series' ],
            '40' => ['mark_id' => '5', 'title' => '5 series', 'slug' => '5_series' ],
            '41' => ['mark_id' => '5', 'title' => '6 series', 'slug' => '6_series' ],
            '42' => ['mark_id' => '5', 'title' => '7 series', 'slug' => '7_series' ],
            '43' => ['mark_id' => '5', 'title' => 'X1', 'slug' => 'x1' ],
            '44' => ['mark_id' => '5', 'title' => 'X2', 'slug' => 'x2' ],
            '45' => ['mark_id' => '5', 'title' => 'X3', 'slug' => 'x3' ],
            '46' => ['mark_id' => '5', 'title' => 'X4', 'slug' => 'x4' ],
            '47' => ['mark_id' => '5', 'title' => 'X5', 'slug' => 'x5' ],
            '48' => ['mark_id' => '5', 'title' => 'X6', 'slug' => 'x6' ],
            '49' => ['mark_id' => '5', 'title' => 'Z3', 'slug' => 'z3' ],
            '50' => ['mark_id' => '5', 'title' => 'Z4', 'slug' => 'z4' ],

            '51' => ['mark_id' => '6', 'title' => 'BLS', 'slug' => 'bls' ],
            '52' => ['mark_id' => '6', 'title' => 'CTS', 'slug' => 'cts' ],
            '53' => ['mark_id' => '6', 'title' => 'De Ville', 'slug' => 'de_ville' ],
            '54' => ['mark_id' => '6', 'title' => 'DTS', 'slug' => 'dts' ],
            '55' => ['mark_id' => '6', 'title' => 'Eldorado', 'slug' => 'eldorado' ],
            '56' => ['mark_id' => '6', 'title' => 'Escalade', 'slug' => 'escalade' ],
            '57' => ['mark_id' => '6', 'title' => 'Seville', 'slug' => 'seville' ],
            '58' => ['mark_id' => '6', 'title' => 'SRX', 'slug' => 'srx' ],
            '59' => ['mark_id' => '6', 'title' => 'STS', 'slug' => 'sts' ],
            '60' => ['mark_id' => '6', 'title' => 'XLR', 'slug' => 'xlr' ],

            '61' => ['mark_id' => '7', 'title' => 'Amulet', 'slug' => 'amulet' ],
            '62' => ['mark_id' => '7', 'title' => 'Eastar', 'slug' => 'eastar' ],
            '63' => ['mark_id' => '7', 'title' => 'Fora', 'slug' => 'fora' ],
            '64' => ['mark_id' => '7', 'title' => 'Kimo', 'slug' => 'kimo' ],
            '65' => ['mark_id' => '7', 'title' => 'M11', 'slug' => 'm11' ],
            '66' => ['mark_id' => '7', 'title' => 'QQ', 'slug' => 'qq' ],

            '67' => ['mark_id' => '8', 'title' => 'Astro', 'slug' => 'astro' ],
            '68' => ['mark_id' => '8', 'title' => 'Aveo', 'slug' => 'aveo' ],
            '69' => ['mark_id' => '8', 'title' => 'Camaro', 'slug' => 'camaro' ],
            '70' => ['mark_id' => '8', 'title' => 'Captiva', 'slug' => 'captiva' ],
            '71' => ['mark_id' => '8', 'title' => 'Cavalier', 'slug' => 'cavalier' ],
            '72' => ['mark_id' => '8', 'title' => 'Cobalt', 'slug' => 'cobalt' ],
            '73' => ['mark_id' => '8', 'title' => 'Corvette', 'slug' => 'corvette' ],
            '74' => ['mark_id' => '8', 'title' => 'Epica', 'slug' => 'epica' ],
            '75' => ['mark_id' => '8', 'title' => 'Impala', 'slug' => 'impala' ],
            '76' => ['mark_id' => '8', 'title' => 'Lacetti', 'slug' => 'lacetti' ],
            '77' => ['mark_id' => '8', 'title' => 'Malibu', 'slug' => 'malibu' ],

            '78' => ['mark_id' => '9', 'title' => '200', 'slug' => '200' ],
            '79' => ['mark_id' => '9', 'title' => '300C', 'slug' => '300c' ],
            '80' => ['mark_id' => '9', 'title' => '300M', 'slug' => '300m' ],
            '81' => ['mark_id' => '9', 'title' => 'Aspen', 'slug' => 'aspen' ],
            '82' => ['mark_id' => '9', 'title' => 'Concorde', 'slug' => 'concorde' ],
            '83' => ['mark_id' => '9', 'title' => 'Crossfire', 'slug' => 'crossfire' ],
            '84' => ['mark_id' => '9', 'title' => 'Voyager', 'slug' => 'voyager' ],

            '85' => ['mark_id' => '10', 'title' => 'Berlingo', 'slug' => 'berlingo' ],
            '86' => ['mark_id' => '10', 'title' => 'C-Crosser', 'slug' => 'c-crosser' ],
            '87' => ['mark_id' => '10', 'title' => 'C1', 'slug' => 'c1' ],
            '88' => ['mark_id' => '10', 'title' => 'C2', 'slug' => 'c2' ],
            '89' => ['mark_id' => '10', 'title' => 'C3', 'slug' => 'c3' ],
            '90' => ['mark_id' => '10', 'title' => 'C4', 'slug' => 'c4' ],
            '91' => ['mark_id' => '10', 'title' => 'C5', 'slug' => 'c5' ],
            '92' => ['mark_id' => '10', 'title' => 'C6', 'slug' => 'c6' ],
            '93' => ['mark_id' => '10', 'title' => 'C8', 'slug' => 'c8' ],

            '94' => ['mark_id' => '11', 'title' => 'Espero', 'slug' => 'espero' ],
            '95' => ['mark_id' => '11', 'title' => 'Evanda', 'slug' => 'evanda' ],
            '96' => ['mark_id' => '11', 'title' => 'Kalos', 'slug' => 'kalos' ],
            '97' => ['mark_id' => '11', 'title' => 'Lanos', 'slug' => 'lanos' ],
            '98' => ['mark_id' => '11', 'title' => 'Leganza', 'slug' => 'leganza' ],
            '99' => ['mark_id' => '11', 'title' => 'Magnus', 'slug' => 'magnus' ],
            '100' => ['mark_id' => '11', 'title' => 'Matiz', 'slug' => 'matiz' ],
            '101' => ['mark_id' => '11', 'title' => 'Nexia', 'slug' => 'nexia' ],
            '102' => ['mark_id' => '11', 'title' => 'Nubira', 'slug' => 'nubira' ],
            '103' => ['mark_id' => '11', 'title' => 'Rezzo', 'slug' => 'rezzo' ],
            '104' => ['mark_id' => '11', 'title' => 'Sens', 'slug' => 'sens' ],

            '105' => ['mark_id' => '12', 'title' => 'Avenger', 'slug' => 'avenger' ],
            '106' => ['mark_id' => '12', 'title' => 'Caliber', 'slug' => 'caliber' ],
            '107' => ['mark_id' => '12', 'title' => 'Caliber SRT4', 'slug' => 'caliber_srt4' ],
            '108' => ['mark_id' => '12', 'title' => 'Challenger', 'slug' => 'challenger' ],
            '109' => ['mark_id' => '12', 'title' => 'Charger', 'slug' => 'charger' ],
            '110' => ['mark_id' => '12', 'title' => 'Dakota', 'slug' => 'dakota' ],
            '111' => ['mark_id' => '12', 'title' => 'Journey', 'slug' => 'journey' ],
            '112' => ['mark_id' => '12', 'title' => 'Magnum', 'slug' => 'magnum' ],
            '113' => ['mark_id' => '12', 'title' => 'Nitro', 'slug' => 'nitro' ],
            '114' => ['mark_id' => '12', 'title' => 'Ram 1500', 'slug' => 'ram_1500' ],
            '115' => ['mark_id' => '12', 'title' => 'Ram 2500', 'slug' => 'ram_2500' ],
            '116' => ['mark_id' => '12', 'title' => 'Ram SRT10', 'slug' => 'ram_srt10' ],
            '117' => ['mark_id' => '12', 'title' => 'Viper', 'slug' => 'viper' ],

            '118' => ['mark_id' => '13', 'title' => 'C-Max', 'slug' => 'c-max' ],
            '119' => ['mark_id' => '13', 'title' => 'Cougar', 'slug' => 'cougar' ],
            '120' => ['mark_id' => '13', 'title' => 'Escape', 'slug' => 'escape' ],
            '121' => ['mark_id' => '13', 'title' => 'Explorer', 'slug' => 'explorer' ],
            '122' => ['mark_id' => '13', 'title' => 'Fiesta', 'slug' => 'fiesta' ],
            '123' => ['mark_id' => '13', 'title' => 'Focus', 'slug' => 'focus' ],
            '124' => ['mark_id' => '13', 'title' => 'Fusion', 'slug' => 'fusion' ],
            '125' => ['mark_id' => '13', 'title' => 'GT', 'slug' => 'gt' ],
            '126' => ['mark_id' => '13', 'title' => 'Maverick', 'slug' => 'maverick' ],
            '127' => ['mark_id' => '13', 'title' => 'Mondeo', 'slug' => 'mondeo' ],
            '128' => ['mark_id' => '13', 'title' => 'Mustang', 'slug' => 'mustang' ],

            '129' => ['mark_id' => '14', 'title' => 'Accord', 'slug' => 'accord' ],
            '130' => ['mark_id' => '14', 'title' => 'Civic', 'slug' => 'civic' ],
            '131' => ['mark_id' => '14', 'title' => 'CR-V', 'slug' => 'cr-v' ],
            '132' => ['mark_id' => '14', 'title' => 'CR-Z', 'slug' => 'cr-z' ],
            '133' => ['mark_id' => '14', 'title' => 'Legend', 'slug' => 'legend' ],
            '134' => ['mark_id' => '14', 'title' => 'Pilot', 'slug' => 'pilot' ],
            '135' => ['mark_id' => '14', 'title' => 'Prelude', 'slug' => 'prelude' ],
            '136' => ['mark_id' => '14', 'title' => 'S2000', 'slug' => 's2000' ],

            '137' => ['mark_id' => '15', 'title' => 'Accent', 'slug' => 'accent' ],
            '138' => ['mark_id' => '15', 'title' => 'Azera', 'slug' => 'azera' ],
            '139' => ['mark_id' => '15', 'title' => 'Coupe', 'slug' => 'coupe' ],
            '140' => ['mark_id' => '15', 'title' => 'Getz', 'slug' => 'getz' ],
            '141' => ['mark_id' => '15', 'title' => 'H1', 'slug' => 'h1' ],
            '142' => ['mark_id' => '15', 'title' => 'Sonata', 'slug' => 'sonata' ],

            '143' => ['mark_id' => '16', 'title' => 'S-Type', 'slug' => 's-type' ],
            '144' => ['mark_id' => '16', 'title' => 'X-Type', 'slug' => 'x-type' ],
            '145' => ['mark_id' => '16', 'title' => 'XF', 'slug' => 'xf' ],
            '146' => ['mark_id' => '16', 'title' => 'XJ', 'slug' => 'xj' ],
            '147' => ['mark_id' => '16', 'title' => 'XK', 'slug' => 'xk' ],

            '148' => ['mark_id' => '17', 'title' => 'Cherokee', 'slug' => 'cherokee' ],
            '149' => ['mark_id' => '17', 'title' => 'Commander', 'slug' => 'commander' ],
            '150' => ['mark_id' => '17', 'title' => 'Compass', 'slug' => 'compass' ],
            '151' => ['mark_id' => '17', 'title' => 'Grand Cherokee', 'slug' => 'grand_cherokee' ],
            '152' => ['mark_id' => '17', 'title' => 'Patriot', 'slug' => 'patriot' ],

            '153' => ['mark_id' => '18', 'title' => 'Defender', 'slug' => 'defender' ],
            '154' => ['mark_id' => '18', 'title' => 'Discovery 2', 'slug' => 'discovery_2' ],
            '155' => ['mark_id' => '18', 'title' => 'Discovery 4', 'slug' => 'discovery_4' ],
            '156' => ['mark_id' => '18', 'title' => 'Evoque', 'slug' => 'evoque' ],
            '157' => ['mark_id' => '18', 'title' => 'Freelander', 'slug' => 'freelander' ],
            '158' => ['mark_id' => '18', 'title' => 'Freelander 2', 'slug' => 'freelander_2' ],
            '159' => ['mark_id' => '18', 'title' => 'Range Rover', 'slug' => 'range_rover' ],
            '160' => ['mark_id' => '18', 'title' => 'Range Rover Sport', 'slug' => 'range_rover_sport' ],

            '161' => ['mark_id' => '19', 'title' => 'CT200h', 'slug' => 'ct200h' ],
            '162' => ['mark_id' => '19', 'title' => 'ES300', 'slug' => 'es300' ],
            '163' => ['mark_id' => '19', 'title' => 'ES330', 'slug' => 'es330' ],
            '164' => ['mark_id' => '19', 'title' => 'ES350', 'slug' => 'es350' ],
            '165' => ['mark_id' => '19', 'title' => 'GS300', 'slug' => 'gs300' ],
            '166' => ['mark_id' => '19', 'title' => 'GS350', 'slug' => 'gs350' ],
            '167' => ['mark_id' => '19', 'title' => 'GS400', 'slug' => 'gs400' ],
            '168' => ['mark_id' => '19', 'title' => 'GS430', 'slug' => 'gs430' ],
            '169' => ['mark_id' => '19', 'title' => 'GS450h', 'slug' => 'gs450h' ],
            '170' => ['mark_id' => '19', 'title' => 'GS460', 'slug' => 'gs460' ],
            '171' => ['mark_id' => '19', 'title' => 'GX460', 'slug' => 'gx460' ],
            '172' => ['mark_id' => '19', 'title' => 'GX470', 'slug' => 'gx470' ],
            '173' => ['mark_id' => '19', 'title' => 'IS-F', 'slug' => 'is-f' ],
            '174' => ['mark_id' => '19', 'title' => 'IS200', 'slug' => 'is200' ],
            '175' => ['mark_id' => '19', 'title' => 'IS300', 'slug' => 'is300' ],
            '176' => ['mark_id' => '19', 'title' => 'IS350', 'slug' => 'is350' ],
            '177' => ['mark_id' => '19', 'title' => 'LFA', 'slug' => 'lfa' ],
            '178' => ['mark_id' => '19', 'title' => 'LS400', 'slug' => 'ls400' ],
            '179' => ['mark_id' => '19', 'title' => 'LS460', 'slug' => 'ls460' ],
            '180' => ['mark_id' => '19', 'title' => 'LS600h', 'slug' => 'ls600h' ],
            '181' => ['mark_id' => '19', 'title' => 'LX470', 'slug' => 'lx470' ],
            '182' => ['mark_id' => '19', 'title' => 'LX570', 'slug' => 'lx570' ],

            '183' => ['mark_id' => '20', 'title' => '3', 'slug' => '3' ],
            '184' => ['mark_id' => '20', 'title' => '323', 'slug' => '323' ],
            '185' => ['mark_id' => '20', 'title' => '5', 'slug' => '5' ],
            '186' => ['mark_id' => '20', 'title' => '6', 'slug' => '6' ],
            '187' => ['mark_id' => '20', 'title' => '626', 'slug' => '626' ],
            '188' => ['mark_id' => '20', 'title' => 'B-Series', 'slug' => 'b-series' ],
            '189' => ['mark_id' => '20', 'title' => 'CX-5', 'slug' => 'cx-5' ],
            '190' => ['mark_id' => '20', 'title' => 'CX-7', 'slug' => 'cx-7' ],
            '191' => ['mark_id' => '20', 'title' => 'CX-9', 'slug' => 'cx-9' ],
            '192' => ['mark_id' => '20', 'title' => 'MPV', 'slug' => 'mpv' ],
            '193' => ['mark_id' => '20', 'title' => 'MX-5 Miata', 'slug' => 'mx-5_miata' ],
            '194' => ['mark_id' => '20', 'title' => 'Premacy', 'slug' => 'premacy' ],
            '195' => ['mark_id' => '20', 'title' => 'RX-7', 'slug' => 'rx-7' ],
            '196' => ['mark_id' => '20', 'title' => 'RX-8', 'slug' => 'rx-8' ],
            '197' => ['mark_id' => '20', 'title' => 'Tribute', 'slug' => 'tribute' ],

            '198' => ['mark_id' => '21', 'title' => 'A-Klasse (W168)', 'slug' => 'a-klasse_(w168)' ],
            '199' => ['mark_id' => '21', 'title' => 'A-Klasse (W169)', 'slug' => 'a-klasse_(w169)' ],
            '200' => ['mark_id' => '21', 'title' => 'B-Klasse (W245)', 'slug' => 'b-klasse_(w245)' ],
            '201' => ['mark_id' => '21', 'title' => 'B-Klasse (W246)', 'slug' => 'b-klasse_(w246)' ],
            '202' => ['mark_id' => '21', 'title' => 'C-Klasse (CL203)', 'slug' => 'c-klasse_(cl203)' ],
            '203' => ['mark_id' => '21', 'title' => 'C-Klasse (W202)', 'slug' => 'c-klasse_(w202)' ],
            '204' => ['mark_id' => '21', 'title' => 'C-Klasse (W203)', 'slug' => 'c-klasse_(w203)' ],
            '205' => ['mark_id' => '21', 'title' => 'C-Klasse (W204)', 'slug' => 'c-klasse_(w204)' ],
            '206' => ['mark_id' => '21', 'title' => 'CL-Klasse (C140)', 'slug' => 'cl-klasse_(c140)' ],
            '207' => ['mark_id' => '21', 'title' => 'CL-Klasse (C215)', 'slug' => 'cl-klasse_(c215)' ],
            '208' => ['mark_id' => '21', 'title' => 'CL-Klasse (C216)', 'slug' => 'cl-klasse_(c216)' ],
            '209' => ['mark_id' => '21', 'title' => 'CLC-Klasse', 'slug' => 'clc-klasse' ],
            '210' => ['mark_id' => '21', 'title' => 'E-Klasse (W210)', 'slug' => 'e-klasse_(w210)' ],
            '211' => ['mark_id' => '21', 'title' => 'E-Klasse (W211)', 'slug' => 'e-klasse_(w211)' ],
            '212' => ['mark_id' => '21', 'title' => 'E-Klasse (W212)', 'slug' => 'e-klasse_(w212)' ],
            '213' => ['mark_id' => '21', 'title' => 'G-Klasse (W463)', 'slug' => 'g-klasse_(w463)' ],
            '214' => ['mark_id' => '21', 'title' => 'GL-Klasse (X164)', 'slug' => 'gl-klasse_(x164)' ],
            '215' => ['mark_id' => '21', 'title' => 'GLK-Klasse (X204)', 'slug' => 'glk-klasse_(x204)' ],

            '216' => ['mark_id' => '22', 'title' => 'ASX', 'slug' => 'asx' ],
            '217' => ['mark_id' => '22', 'title' => 'Carisma', 'slug' => 'carisma' ],
            '218' => ['mark_id' => '22', 'title' => 'Colt', 'slug' => 'colt' ],
            '219' => ['mark_id' => '22', 'title' => 'Eclipse', 'slug' => 'eclipse' ],
            '220' => ['mark_id' => '22', 'title' => 'Endeavor', 'slug' => 'endeavor' ],
            '221' => ['mark_id' => '22', 'title' => 'Galant', 'slug' => 'galant' ],
            '222' => ['mark_id' => '22', 'title' => 'Grandis', 'slug' => 'grandis' ],
            '223' => ['mark_id' => '22', 'title' => 'L200', 'slug' => 'l200' ],
            '224' => ['mark_id' => '22', 'title' => 'Lancer', 'slug' => 'lancer' ],
            '225' => ['mark_id' => '22', 'title' => 'Lancer Evo IX', 'slug' => 'lancer_evo_ix' ],
            '226' => ['mark_id' => '22', 'title' => 'Lancer Evo VII', 'slug' => 'lancer_evo_vii' ],
            '227' => ['mark_id' => '22', 'title' => 'Lancer Evo VIII', 'slug' => 'lancer_evo_viii' ],
            '228' => ['mark_id' => '22', 'title' => 'Lancer Evo X', 'slug' => 'lancer_evo_x' ],
            '229' => ['mark_id' => '22', 'title' => 'Outlander', 'slug' => 'outlander' ],
            '230' => ['mark_id' => '22', 'title' => 'Outlander XL', 'slug' => 'outlander_xl' ],
            '231' => ['mark_id' => '22', 'title' => 'Pajero', 'slug' => 'pajero' ],
            '232' => ['mark_id' => '22', 'title' => 'Pajero Sport', 'slug' => 'pajero_sport' ],

            '233' => ['mark_id' => '23', 'title' => '350Z', 'slug' => '350z' ],
            '234' => ['mark_id' => '23', 'title' => '370Z', 'slug' => '370z' ],
            '235' => ['mark_id' => '23', 'title' => 'Almera', 'slug' => 'almera' ],
            '236' => ['mark_id' => '23', 'title' => 'Altima', 'slug' => 'altima' ],
            '237' => ['mark_id' => '23', 'title' => 'Armada', 'slug' => 'armada' ],
            '238' => ['mark_id' => '23', 'title' => 'Cube Cubic', 'slug' => 'cube_cubic' ],
            '239' => ['mark_id' => '23', 'title' => 'Cube I', 'slug' => 'cube_i' ],
            '240' => ['mark_id' => '23', 'title' => 'Cube II', 'slug' => 'cube_ii' ],
            '241' => ['mark_id' => '23', 'title' => 'Cube III', 'slug' => 'cube_iii' ],
            '242' => ['mark_id' => '23', 'title' => 'Frontier', 'slug' => 'frontier' ],
            '243' => ['mark_id' => '23', 'title' => 'GT-R', 'slug' => 'gt-r' ],
            '244' => ['mark_id' => '23', 'title' => 'Juke', 'slug' => 'juke' ],
            '245' => ['mark_id' => '23', 'title' => 'Leaf', 'slug' => 'leaf' ],
            '246' => ['mark_id' => '23', 'title' => 'Murano', 'slug' => 'murano' ],
            '247' => ['mark_id' => '23', 'title' => 'Note', 'slug' => 'note' ],
            '248' => ['mark_id' => '23', 'title' => 'Primera', 'slug' => 'primera' ],

            '249' => ['mark_id' => '24', 'title' => 'Agila', 'slug' => 'agila' ],
            '250' => ['mark_id' => '24', 'title' => 'Antara', 'slug' => 'antara' ],
            '251' => ['mark_id' => '24', 'title' => 'Astra', 'slug' => 'astra' ],
            '252' => ['mark_id' => '24', 'title' => 'Combo Tour', 'slug' => 'combo_tour' ],
            '253' => ['mark_id' => '24', 'title' => 'Corsa', 'slug' => 'corsa' ],
            '254' => ['mark_id' => '24', 'title' => 'Frontera', 'slug' => 'frontera' ],
            '255' => ['mark_id' => '24', 'title' => 'Insignia', 'slug' => 'insignia' ],
            '256' => ['mark_id' => '24', 'title' => 'Meriva', 'slug' => 'meriva' ],
            '257' => ['mark_id' => '24', 'title' => 'Mokka', 'slug' => 'mokka' ],
            '258' => ['mark_id' => '24', 'title' => 'Omega', 'slug' => 'omega' ],
            '259' => ['mark_id' => '24', 'title' => 'Signum', 'slug' => 'signum' ],
            '260' => ['mark_id' => '24', 'title' => 'Vectra', 'slug' => 'vectra' ],
            '261' => ['mark_id' => '24', 'title' => 'Vivaro', 'slug' => 'vivaro' ],
            '262' => ['mark_id' => '24', 'title' => 'Zafira', 'slug' => 'zafira' ],
            '263' => ['mark_id' => '24', 'title' => 'Zafira Tourier', 'slug' => 'zafira_tourier' ],

            '264' => ['mark_id' => '25', 'title' => '1007', 'slug' => '1007' ],
            '265' => ['mark_id' => '25', 'title' => '107', 'slug' => '107' ],
            '266' => ['mark_id' => '25', 'title' => '206', 'slug' => '206' ],
            '267' => ['mark_id' => '25', 'title' => '207', 'slug' => '207' ],
            '268' => ['mark_id' => '25', 'title' => '3008', 'slug' => '3008' ],
            '269' => ['mark_id' => '25', 'title' => '307', 'slug' => '307' ],
            '270' => ['mark_id' => '25', 'title' => '308', 'slug' => '308' ],
            '271' => ['mark_id' => '25', 'title' => '4007', 'slug' => '4007' ],
            '272' => ['mark_id' => '25', 'title' => '4008', 'slug' => '4008' ],
            '273' => ['mark_id' => '25', 'title' => '406', 'slug' => '406' ],
            '274' => ['mark_id' => '25', 'title' => '407', 'slug' => '407' ],
            '275' => ['mark_id' => '25', 'title' => '508', 'slug' => '508' ],
            '276' => ['mark_id' => '25', 'title' => '607', 'slug' => '607' ],
            '277' => ['mark_id' => '25', 'title' => '807', 'slug' => '807' ],
            '278' => ['mark_id' => '25', 'title' => 'Boxer', 'slug' => 'boxer' ],
            '279' => ['mark_id' => '25', 'title' => 'Partner', 'slug' => 'partner' ],
            '280' => ['mark_id' => '25', 'title' => 'RCZ Sport', 'slug' => 'rcz_sport' ],

            '281' => ['mark_id' => '26', 'title' => '911', 'slug' => '911' ],
            '282' => ['mark_id' => '26', 'title' => 'Boxster', 'slug' => 'boxster' ],
            '283' => ['mark_id' => '26', 'title' => 'Cayenne', 'slug' => 'cayenne' ],
            '284' => ['mark_id' => '26', 'title' => 'Cayman', 'slug' => 'cayman' ],
            '285' => ['mark_id' => '26', 'title' => 'Panamera', 'slug' => 'panamera' ],

            '286' => ['mark_id' => '27', 'title' => 'Avantime', 'slug' => 'avantime' ],
            '287' => ['mark_id' => '27', 'title' => 'Clio', 'slug' => 'clio' ],
            '288' => ['mark_id' => '27', 'title' => 'Duster', 'slug' => 'duster' ],
            '289' => ['mark_id' => '27', 'title' => 'Espace', 'slug' => 'espace' ],
            '290' => ['mark_id' => '27', 'title' => 'Fluence', 'slug' => 'fluence' ],
            '291' => ['mark_id' => '27', 'title' => 'Kangoo', 'slug' => 'kangoo' ],
            '292' => ['mark_id' => '27', 'title' => 'Kangoo Compact', 'slug' => 'kangoo_compact' ],
            '293' => ['mark_id' => '27', 'title' => 'Koleos', 'slug' => 'koleos' ],
            '294' => ['mark_id' => '27', 'title' => 'Laguna', 'slug' => 'laguna' ],
            '295' => ['mark_id' => '27', 'title' => 'Latitude', 'slug' => 'latitude' ],
            '296' => ['mark_id' => '27', 'title' => 'Logan', 'slug' => 'logan' ],
            '297' => ['mark_id' => '27', 'title' => 'Master', 'slug' => 'master' ],
            '298' => ['mark_id' => '27', 'title' => 'Megane', 'slug' => 'megane' ],
            '299' => ['mark_id' => '27', 'title' => 'Modus', 'slug' => 'modus' ],
            '300' => ['mark_id' => '27', 'title' => 'Sandero', 'slug' => 'sandero' ],
            '301' => ['mark_id' => '27', 'title' => 'Sandero Stepway', 'slug' => 'sandero_stepway' ],
            '302' => ['mark_id' => '27', 'title' => 'Scenic', 'slug' => 'scenic' ],
            '303' => ['mark_id' => '27', 'title' => 'Symbol', 'slug' => 'symbol' ],
            '304' => ['mark_id' => '27', 'title' => 'Trafic', 'slug' => 'trafic' ],
            '305' => ['mark_id' => '27', 'title' => 'Twingo', 'slug' => 'twingo' ],
            '306' => ['mark_id' => '27', 'title' => 'Vel Satis', 'slug' => 'vel_satis' ],

            '307' => ['mark_id' => '28', 'title' => 'Fabia', 'slug' => 'fabia' ],
            '308' => ['mark_id' => '28', 'title' => 'Felicia', 'slug' => 'felicia' ],
            '309' => ['mark_id' => '28', 'title' => 'Octavia', 'slug' => 'octavia' ],
            '310' => ['mark_id' => '28', 'title' => 'Octavia Scout', 'slug' => 'octavia_scout' ],
            '311' => ['mark_id' => '28', 'title' => 'Octavia Tour', 'slug' => 'octavia_tour' ],
            '312' => ['mark_id' => '28', 'title' => 'Praktik', 'slug' => 'praktik' ],
            '313' => ['mark_id' => '28', 'title' => 'Roomster', 'slug' => 'roomster' ],
            '314' => ['mark_id' => '28', 'title' => 'Superb', 'slug' => 'superb' ],
            '315' => ['mark_id' => '28', 'title' => 'Yeti', 'slug' => 'yeti' ],

            '316' => ['mark_id' => '29', 'title' => '7-series', 'slug' => '7-series' ],
            '317' => ['mark_id' => '29', 'title' => 'Baja', 'slug' => 'baja' ],
            '318' => ['mark_id' => '29', 'title' => 'Forester', 'slug' => 'forester' ],
            '319' => ['mark_id' => '29', 'title' => 'Impreza', 'slug' => 'impreza' ],
            '320' => ['mark_id' => '29', 'title' => 'Justy', 'slug' => 'justy' ],
            '321' => ['mark_id' => '29', 'title' => 'Legacy', 'slug' => 'legacy' ],
            '322' => ['mark_id' => '29', 'title' => 'Outback', 'slug' => 'outback' ],
            '323' => ['mark_id' => '29', 'title' => 'Traviq', 'slug' => 'traviq' ],
            '324' => ['mark_id' => '29', 'title' => 'Tribeca', 'slug' => 'tribeca' ],
            '325' => ['mark_id' => '29', 'title' => 'XV', 'slug' => 'xv' ],

            '326' => ['mark_id' => '30', 'title' => 'Alphard', 'slug' => 'alphard' ],
            '327' => ['mark_id' => '30', 'title' => 'Auris', 'slug' => 'auris' ],
            '328' => ['mark_id' => '30', 'title' => 'Avalon', 'slug' => 'avalon' ],
            '329' => ['mark_id' => '30', 'title' => 'Avensis', 'slug' => 'avensis' ],
            '330' => ['mark_id' => '30', 'title' => 'Avensis Verso', 'slug' => 'avensis_verso' ],
            '331' => ['mark_id' => '30', 'title' => 'Aygo', 'slug' => 'aygo' ],
            '332' => ['mark_id' => '30', 'title' => 'Camry', 'slug' => 'camry' ],
            '333' => ['mark_id' => '30', 'title' => 'Celica', 'slug' => 'celica' ],
            '334' => ['mark_id' => '30', 'title' => 'Corolla', 'slug' => 'corolla' ],
            '335' => ['mark_id' => '30', 'title' => 'Corolla Verso', 'slug' => 'corolla_verso' ],
            '336' => ['mark_id' => '30', 'title' => 'FJ Cruiser', 'slug' => 'fj_cruiser' ],
            '337' => ['mark_id' => '30', 'title' => 'Fortuner', 'slug' => 'fortuner' ],
            '338' => ['mark_id' => '30', 'title' => 'Highlander', 'slug' => 'highlander' ],
            '339' => ['mark_id' => '30', 'title' => 'Hilux', 'slug' => 'hilux' ],
            '340' => ['mark_id' => '30', 'title' => 'IQ', 'slug' => 'iq' ],
            '341' => ['mark_id' => '30', 'title' => 'Land Cruiser 100 GX', 'slug' => 'land_cruiser_100_gx' ],
            '342' => ['mark_id' => '30', 'title' => 'Land Cruiser 100 VX', 'slug' => 'land_cruiser_100_vx' ],
            '343' => ['mark_id' => '30', 'title' => 'Land Cruiser 200', 'slug' => 'land_cruiser_200' ],
            '344' => ['mark_id' => '30', 'title' => 'Land Cruiser 80', 'slug' => 'land_cruiser_80' ],
            '345' => ['mark_id' => '30', 'title' => 'Land Cruiser 90', 'slug' => 'land_cruiser_90' ],
            '346' => ['mark_id' => '30', 'title' => 'Land Cruiser Prado', 'slug' => 'land_cruiser_prado' ],
            '347' => ['mark_id' => '30', 'title' => 'Matrix', 'slug' => 'matrix' ],
            '348' => ['mark_id' => '30', 'title' => 'MR2', 'slug' => 'mr2' ],

            '349' => ['mark_id' => '31', 'title' => '8-series', 'slug' => '8-series' ],
            '350' => ['mark_id' => '31', 'title' => 'Amarok', 'slug' => 'amarok' ],
            '351' => ['mark_id' => '31', 'title' => 'Beetle (A4)', 'slug' => 'beetle_(a4)' ],
            '352' => ['mark_id' => '31', 'title' => 'Beetle (A5)', 'slug' => 'beetle_(a5)' ],
            '353' => ['mark_id' => '31', 'title' => 'Bora', 'slug' => 'bora' ],
            '354' => ['mark_id' => '31', 'title' => 'Caddy', 'slug' => 'caddy' ],
            '355' => ['mark_id' => '31', 'title' => 'Crafter', 'slug' => 'crafter' ],
            '356' => ['mark_id' => '31', 'title' => 'CrossGolf', 'slug' => 'crossgolf' ],
            '357' => ['mark_id' => '31', 'title' => 'CrossPolo', 'slug' => 'crosspolo' ],
            '358' => ['mark_id' => '31', 'title' => 'CrossTouran', 'slug' => 'crosstouran' ],
            '359' => ['mark_id' => '31', 'title' => 'Eos', 'slug' => 'eos' ],
            '360' => ['mark_id' => '31', 'title' => 'Fox', 'slug' => 'fox' ],
            '361' => ['mark_id' => '31', 'title' => 'Golf', 'slug' => 'golf' ],
            '362' => ['mark_id' => '31', 'title' => 'Jetta', 'slug' => 'jetta' ],
            '363' => ['mark_id' => '31', 'title' => 'Lupo', 'slug' => 'lupo' ],
            '364' => ['mark_id' => '31', 'title' => 'Multivan', 'slug' => 'multivan' ],
            '365' => ['mark_id' => '31', 'title' => 'Passat', 'slug' => 'passat' ],
            '366' => ['mark_id' => '31', 'title' => 'Pointer', 'slug' => 'pointer' ],
            '367' => ['mark_id' => '31', 'title' => 'Polo', 'slug' => 'polo' ],
            '368' => ['mark_id' => '31', 'title' => 'Polo Sedan', 'slug' => 'polo_sedan' ],

            '369' => ['mark_id' => '32', 'title' => 'C30', 'slug' => 'c30' ],
            '370' => ['mark_id' => '32', 'title' => 'C70 Convertible', 'slug' => 'c70_convertible' ],
            '371' => ['mark_id' => '32', 'title' => 'C70 Coupe', 'slug' => 'c70_coupe' ],
            '372' => ['mark_id' => '32', 'title' => 'S40', 'slug' => 's40' ],
            '373' => ['mark_id' => '32', 'title' => 'S60', 'slug' => 's60' ],
            '374' => ['mark_id' => '32', 'title' => 'S70', 'slug' => 's70' ],
            '375' => ['mark_id' => '32', 'title' => 'S80', 'slug' => 's80' ],
            '376' => ['mark_id' => '32', 'title' => 'S90', 'slug' => 's90' ],
            '377' => ['mark_id' => '32', 'title' => 'V40', 'slug' => 'v40' ],
            '378' => ['mark_id' => '32', 'title' => 'V50', 'slug' => 'v50' ],
            '379' => ['mark_id' => '32', 'title' => 'V70', 'slug' => 'v70' ],
            '380' => ['mark_id' => '32', 'title' => 'V90', 'slug' => 'v90' ],
            '381' => ['mark_id' => '32', 'title' => 'XC60', 'slug' => 'xc60' ],
            '382' => ['mark_id' => '32', 'title' => 'XC70', 'slug' => 'xc70' ],
            '383' => ['mark_id' => '32', 'title' => 'XC90', 'slug' => 'xc90' ],
        ];

        foreach ($models as $id => $data) {
            CarModel::create([
                'id' => $id,
                'car_mark_id' => $data['mark_id'],
                'title' => $data['title'],
                'slug' => $data['slug'],
            ]);
        }



    }
}