<?php

use Illuminate\Database\Seeder;
use App\CarModel;

class ModelTableSeeder extends Seeder {
    public function run()
    {
        DB::table('car_models')->delete();

        $models = [
            '1'  => ['mark_id' => 1, 'title' => 'EL' ],
            '2'  => ['mark_id' => 1, 'title' => 'Integra' ],
            '3'  => ['mark_id' => 1, 'title' => 'MDX' ],
            '4'  => ['mark_id' => 1, 'title' => 'NSX' ],
            '5'  => ['mark_id' => 1, 'title' => 'RDX' ],
            '6'  => ['mark_id' => 1, 'title' => 'RSX' ],
            '7'  => ['mark_id' => 1, 'title' => 'ZDX' ],

            '8'  => ['mark_id' => 2, 'title' => 'Brera' ],
            '9'  => ['mark_id' => 2, 'title' => 'Giulietta' ],
            '10' => ['mark_id' => 2, 'title' => 'GT' ],
            '11' => ['mark_id' => 2, 'title' => 'Spider' ],

            '12' => ['mark_id' => 3, 'title' => 'A1' ],
            '13' => ['mark_id' => 3, 'title' => 'A2' ],
            '14' => ['mark_id' => 3, 'title' => 'A3' ],
            '15' => ['mark_id' => 3, 'title' => 'A4' ],
            '16' => ['mark_id' => 3, 'title' => 'A5' ],
            '17' => ['mark_id' => 3, 'title' => 'A6' ],
            '18' => ['mark_id' => 3, 'title' => 'A7' ],
            '19' => ['mark_id' => 3, 'title' => 'A8' ],
            '20' => ['mark_id' => 3, 'title' => 'Q3' ],
            '21' => ['mark_id' => 3, 'title' => 'Q5' ],
            '22' => ['mark_id' => 3, 'title' => 'Q7' ],
            '23' => ['mark_id' => 3, 'title' => 'R8' ],
            '24' => ['mark_id' => 3, 'title' => 'S4' ],
            '25' => ['mark_id' => 3, 'title' => 'S5' ],
            '26' => ['mark_id' => 3, 'title' => 'S6' ],
            '28' => ['mark_id' => 3, 'title' => 'S7' ],
            '29' => ['mark_id' => 3, 'title' => 'S8' ],
            '30' => ['mark_id' => 3, 'title' => 'TT' ],

            '31' => ['mark_id' => 4, 'title' => 'Arnage' ],
            '32' => ['mark_id' => 4, 'title' => 'Azure' ],
            '33' => ['mark_id' => 4, 'title' => 'Brooklands' ],
            '34' => ['mark_id' => 4, 'title' => 'Continental' ],
            '35' => ['mark_id' => 4, 'title' => 'Mulsanne' ],

            '36' => ['mark_id' => 5, 'title' => '1 series' ],
            '37' => ['mark_id' => 5, 'title' => '2 series' ],
            '38' => ['mark_id' => 5, 'title' => '3 series' ],
            '39' => ['mark_id' => 5, 'title' => '4 series' ],
            '40' => ['mark_id' => 5, 'title' => '5 series' ],
            '41' => ['mark_id' => 5, 'title' => '6 series' ],
            '42' => ['mark_id' => 5, 'title' => '7 series' ],
            '43' => ['mark_id' => 5, 'title' => 'X1' ],
            '44' => ['mark_id' => 5, 'title' => 'X2' ],
            '45' => ['mark_id' => 5, 'title' => 'X3' ],
            '46' => ['mark_id' => 5, 'title' => 'X4' ],
            '47' => ['mark_id' => 5, 'title' => 'X5' ],
            '48' => ['mark_id' => 5, 'title' => 'X6' ],
            '49' => ['mark_id' => 5, 'title' => 'Z3' ],
            '50' => ['mark_id' => 5, 'title' => 'Z4' ],

            '51' => ['mark_id' => 6, 'title' => 'BLS' ],
            '52' => ['mark_id' => 6, 'title' => 'CTS' ],
            '53' => ['mark_id' => 6, 'title' => 'De Ville' ],
            '54' => ['mark_id' => 6, 'title' => 'DTS' ],
            '55' => ['mark_id' => 6, 'title' => 'Eldorado' ],
            '56' => ['mark_id' => 6, 'title' => 'Escalade' ],
            '57' => ['mark_id' => 6, 'title' => 'Seville' ],
            '58' => ['mark_id' => 6, 'title' => 'SRX' ],
            '59' => ['mark_id' => 6, 'title' => 'STS' ],
            '60' => ['mark_id' => 6, 'title' => 'XLR' ],

            '61' => ['mark_id' => 7, 'title' => 'Amulet' ],
            '62' => ['mark_id' => 7, 'title' => 'Eastar' ],
            '63' => ['mark_id' => 7, 'title' => 'Fora' ],
            '64' => ['mark_id' => 7, 'title' => 'Kimo' ],
            '65' => ['mark_id' => 7, 'title' => 'M11' ],
            '66' => ['mark_id' => 7, 'title' => 'QQ' ],

            '67' => ['mark_id' => 8, 'title' => 'Astro' ],
            '68' => ['mark_id' => 8, 'title' => 'Aveo' ],
            '69' => ['mark_id' => 8, 'title' => 'Camaro' ],
            '70' => ['mark_id' => 8, 'title' => 'Captiva' ],
            '71' => ['mark_id' => 8, 'title' => 'Cavalier' ],
            '72' => ['mark_id' => 8, 'title' => 'Cobalt' ],
            '73' => ['mark_id' => 8, 'title' => 'Corvette' ],
            '74' => ['mark_id' => 8, 'title' => 'Epica' ],
            '75' => ['mark_id' => 8, 'title' => 'Impala' ],
            '76' => ['mark_id' => 8, 'title' => 'Lacetti' ],
            '77' => ['mark_id' => 8, 'title' => 'Malibu' ],

            '78' => ['mark_id' => 9, 'title' => '200' ],
            '79' => ['mark_id' => 9, 'title' => '300C' ],
            '80' => ['mark_id' => 9, 'title' => '300M' ],
            '81' => ['mark_id' => 9, 'title' => 'Aspen' ],
            '82' => ['mark_id' => 9, 'title' => 'Concorde' ],
            '83' => ['mark_id' => 9, 'title' => 'Crossfire' ],
            '84' => ['mark_id' => 9, 'title' => 'Voyager' ],

            '85' => ['mark_id' => 10, 'title' => 'Berlingo' ],
            '86' => ['mark_id' => 10, 'title' => 'C-Crosser' ],
            '87' => ['mark_id' => 10, 'title' => 'C1' ],
            '88' => ['mark_id' => 10, 'title' => 'C2' ],
            '89' => ['mark_id' => 10, 'title' => 'C3' ],
            '90' => ['mark_id' => 10, 'title' => 'C4' ],
            '91' => ['mark_id' => 10, 'title' => 'C5' ],
            '92' => ['mark_id' => 10, 'title' => 'C6' ],
            '93' => ['mark_id' => 10, 'title' => 'C8' ],

            '94' => ['mark_id' => 11, 'title' => 'Espero' ],
            '95' => ['mark_id' => 11, 'title' => 'Evanda' ],
            '96' => ['mark_id' => 11, 'title' => 'Kalos' ],
            '97' => ['mark_id' => 11, 'title' => 'Lanos' ],
            '98' => ['mark_id' => 11, 'title' => 'Leganza' ],
            '99' => ['mark_id' => 11, 'title' => 'Magnus' ],
            '100' => ['mark_id' => 11, 'title' => 'Matiz' ],
            '101' => ['mark_id' => 11, 'title' => 'Nexia' ],
            '102' => ['mark_id' => 11, 'title' => 'Nubira' ],
            '103' => ['mark_id' => 11, 'title' => 'Rezzo' ],
            '104' => ['mark_id' => 11, 'title' => 'Sens' ],

            '105' => ['mark_id' => 12, 'title' => 'Avenger' ],
            '106' => ['mark_id' => 12, 'title' => 'Caliber' ],
            '107' => ['mark_id' => 12, 'title' => 'Caliber SRT4' ],
            '108' => ['mark_id' => 12, 'title' => 'Challenger' ],
            '109' => ['mark_id' => 12, 'title' => 'Charger' ],
            '110' => ['mark_id' => 12, 'title' => 'Dakota' ],
            '111' => ['mark_id' => 12, 'title' => 'Journey' ],
            '112' => ['mark_id' => 12, 'title' => 'Magnum' ],
            '113' => ['mark_id' => 12, 'title' => 'Nitro' ],
            '114' => ['mark_id' => 12, 'title' => 'Ram 1500' ],
            '115' => ['mark_id' => 12, 'title' => 'Ram 2500' ],
            '116' => ['mark_id' => 12, 'title' => 'Ram SRT10' ],
            '117' => ['mark_id' => 12, 'title' => 'Viper' ],

            '118' => ['mark_id' => 13, 'title' => 'C-Max' ],
            '119' => ['mark_id' => 13, 'title' => 'Cougar' ],
            '120' => ['mark_id' => 13, 'title' => 'Escape' ],
            '121' => ['mark_id' => 13, 'title' => 'Explorer' ],
            '122' => ['mark_id' => 13, 'title' => 'Fiesta' ],
            '123' => ['mark_id' => 13, 'title' => 'Focus' ],
            '124' => ['mark_id' => 13, 'title' => 'Fusion' ],
            '125' => ['mark_id' => 13, 'title' => 'GT' ],
            '126' => ['mark_id' => 13, 'title' => 'Maverick' ],
            '127' => ['mark_id' => 13, 'title' => 'Mondeo' ],
            '128' => ['mark_id' => 13, 'title' => 'Mustang' ],

            '129' => ['mark_id' => 14, 'title' => 'Accord' ],
            '130' => ['mark_id' => 14, 'title' => 'Civic' ],
            '131' => ['mark_id' => 14, 'title' => 'CR-V' ],
            '132' => ['mark_id' => 14, 'title' => 'CR-Z' ],
            '133' => ['mark_id' => 14, 'title' => 'Legend' ],
            '134' => ['mark_id' => 14, 'title' => 'Pilot' ],
            '135' => ['mark_id' => 14, 'title' => 'Prelude' ],
            '136' => ['mark_id' => 14, 'title' => 'S2000' ],

            '137' => ['mark_id' => 15, 'title' => 'Accent' ],
            '138' => ['mark_id' => 15, 'title' => 'Azera' ],
            '139' => ['mark_id' => 15, 'title' => 'Coupe' ],
            '140' => ['mark_id' => 15, 'title' => 'Getz' ],
            '141' => ['mark_id' => 15, 'title' => 'H1' ],
            '142' => ['mark_id' => 15, 'title' => 'Sonata' ],

            '143' => ['mark_id' => 16, 'title' => 'S-Type' ],
            '144' => ['mark_id' => 16, 'title' => 'X-Type' ],
            '145' => ['mark_id' => 16, 'title' => 'XF' ],
            '146' => ['mark_id' => 16, 'title' => 'XJ' ],
            '147' => ['mark_id' => 16, 'title' => 'XK' ],

            '148' => ['mark_id' => 17, 'title' => 'Cherokee' ],
            '149' => ['mark_id' => 17, 'title' => 'Commander' ],
            '150' => ['mark_id' => 17, 'title' => 'Compass' ],
            '151' => ['mark_id' => 17, 'title' => 'Grand Cherokee' ],
            '152' => ['mark_id' => 17, 'title' => 'Patriot' ],

            '153' => ['mark_id' => 18, 'title' => 'Defender' ],
            '154' => ['mark_id' => 18, 'title' => 'Discovery 2' ],
            '155' => ['mark_id' => 18, 'title' => 'Discovery 4' ],
            '156' => ['mark_id' => 18, 'title' => 'Evoque' ],
            '157' => ['mark_id' => 18, 'title' => 'Freelander' ],
            '158' => ['mark_id' => 18, 'title' => 'Freelander 2' ],
            '159' => ['mark_id' => 18, 'title' => 'Range Rover' ],
            '160' => ['mark_id' => 18, 'title' => 'Range Rover Sport' ],

            '161' => ['mark_id' => 19, 'title' => 'CT200h' ],
            '162' => ['mark_id' => 19, 'title' => 'ES300' ],
            '163' => ['mark_id' => 19, 'title' => 'ES330' ],
            '164' => ['mark_id' => 19, 'title' => 'ES350' ],
            '165' => ['mark_id' => 19, 'title' => 'GS300' ],
            '166' => ['mark_id' => 19, 'title' => 'GS350' ],
            '167' => ['mark_id' => 19, 'title' => 'GS400' ],
            '168' => ['mark_id' => 19, 'title' => 'GS430' ],
            '169' => ['mark_id' => 19, 'title' => 'GS450h' ],
            '170' => ['mark_id' => 19, 'title' => 'GS460' ],
            '171' => ['mark_id' => 19, 'title' => 'GX460' ],
            '172' => ['mark_id' => 19, 'title' => 'GX470' ],
            '173' => ['mark_id' => 19, 'title' => 'IS-F' ],
            '174' => ['mark_id' => 19, 'title' => 'IS200' ],
            '175' => ['mark_id' => 19, 'title' => 'IS300' ],
            '176' => ['mark_id' => 19, 'title' => 'IS350' ],
            '177' => ['mark_id' => 19, 'title' => 'LFA' ],
            '178' => ['mark_id' => 19, 'title' => 'LS400' ],
            '179' => ['mark_id' => 19, 'title' => 'LS460' ],
            '180' => ['mark_id' => 19, 'title' => 'LS600h' ],
            '181' => ['mark_id' => 19, 'title' => 'LX470' ],
            '182' => ['mark_id' => 19, 'title' => 'LX570' ],

            '183' => ['mark_id' => 20, 'title' => '3' ],
            '184' => ['mark_id' => 20, 'title' => '323' ],
            '185' => ['mark_id' => 20, 'title' => '5' ],
            '186' => ['mark_id' => 20, 'title' => '6' ],
            '187' => ['mark_id' => 20, 'title' => '626' ],
            '188' => ['mark_id' => 20, 'title' => 'B-Series' ],
            '189' => ['mark_id' => 20, 'title' => 'CX-5' ],
            '190' => ['mark_id' => 20, 'title' => 'CX-7' ],
            '191' => ['mark_id' => 20, 'title' => 'CX-9' ],
            '192' => ['mark_id' => 20, 'title' => 'MPV' ],
            '193' => ['mark_id' => 20, 'title' => 'MX-5 Miata' ],
            '194' => ['mark_id' => 20, 'title' => 'Premacy' ],
            '195' => ['mark_id' => 20, 'title' => 'RX-7' ],
            '196' => ['mark_id' => 20, 'title' => 'RX-8' ],
            '197' => ['mark_id' => 20, 'title' => 'Tribute' ],

            '198' => ['mark_id' => 21, 'title' => 'A-Klasse (W168)' ],
            '199' => ['mark_id' => 21, 'title' => 'A-Klasse (W169)' ],
            '200' => ['mark_id' => 21, 'title' => 'B-Klasse (W245)' ],
            '201' => ['mark_id' => 21, 'title' => 'B-Klasse (W246)' ],
            '202' => ['mark_id' => 21, 'title' => 'C-Klasse (CL203)' ],
            '203' => ['mark_id' => 21, 'title' => 'C-Klasse (W202)' ],
            '204' => ['mark_id' => 21, 'title' => 'C-Klasse (W203)' ],
            '205' => ['mark_id' => 21, 'title' => 'C-Klasse (W204)' ],
            '206' => ['mark_id' => 21, 'title' => 'CL-Klasse (C140)' ],
            '207' => ['mark_id' => 21, 'title' => 'CL-Klasse (C215)' ],
            '208' => ['mark_id' => 21, 'title' => 'CL-Klasse (C216)' ],
            '209' => ['mark_id' => 21, 'title' => 'CLC-Klasse' ],
            '210' => ['mark_id' => 21, 'title' => 'E-Klasse (W210)' ],
            '211' => ['mark_id' => 21, 'title' => 'E-Klasse (W211)' ],
            '212' => ['mark_id' => 21, 'title' => 'E-Klasse (W212)' ],
            '213' => ['mark_id' => 21, 'title' => 'G-Klasse (W463)' ],
            '214' => ['mark_id' => 21, 'title' => 'GL-Klasse (X164)' ],
            '215' => ['mark_id' => 21, 'title' => 'GLK-Klasse (X204)' ],

            '216' => ['mark_id' => 22, 'title' => 'ASX' ],
            '217' => ['mark_id' => 22, 'title' => 'Carisma' ],
            '218' => ['mark_id' => 22, 'title' => 'Colt' ],
            '219' => ['mark_id' => 22, 'title' => 'Eclipse' ],
            '220' => ['mark_id' => 22, 'title' => 'Endeavor' ],
            '221' => ['mark_id' => 22, 'title' => 'Galant' ],
            '222' => ['mark_id' => 22, 'title' => 'Grandis' ],
            '223' => ['mark_id' => 22, 'title' => 'L200' ],
            '224' => ['mark_id' => 22, 'title' => 'Lancer' ],
            '225' => ['mark_id' => 22, 'title' => 'Lancer Evo IX' ],
            '226' => ['mark_id' => 22, 'title' => 'Lancer Evo VII' ],
            '227' => ['mark_id' => 22, 'title' => 'Lancer Evo VIII' ],
            '228' => ['mark_id' => 22, 'title' => 'Lancer Evo X' ],
            '229' => ['mark_id' => 22, 'title' => 'Outlander' ],
            '230' => ['mark_id' => 22, 'title' => 'Outlander XL' ],
            '231' => ['mark_id' => 22, 'title' => 'Pajero' ],
            '232' => ['mark_id' => 22, 'title' => 'Pajero Sport' ],

            '233' => ['mark_id' => 23, 'title' => '350Z' ],
            '234' => ['mark_id' => 23, 'title' => '370Z' ],
            '235' => ['mark_id' => 23, 'title' => 'Almera' ],
            '236' => ['mark_id' => 23, 'title' => 'Altima' ],
            '237' => ['mark_id' => 23, 'title' => 'Armada' ],
            '238' => ['mark_id' => 23, 'title' => 'Cube Cubic' ],
            '239' => ['mark_id' => 23, 'title' => 'Cube I' ],
            '240' => ['mark_id' => 23, 'title' => 'Cube II' ],
            '241' => ['mark_id' => 23, 'title' => 'Cube III' ],
            '242' => ['mark_id' => 23, 'title' => 'Frontier' ],
            '243' => ['mark_id' => 23, 'title' => 'GT-R' ],
            '244' => ['mark_id' => 23, 'title' => 'Juke' ],
            '245' => ['mark_id' => 23, 'title' => 'Leaf' ],
            '246' => ['mark_id' => 23, 'title' => 'Murano' ],
            '247' => ['mark_id' => 23, 'title' => 'Note' ],
            '248' => ['mark_id' => 23, 'title' => 'Primera' ],

            '249' => ['mark_id' => 24, 'title' => 'Agila' ],
            '250' => ['mark_id' => 24, 'title' => 'Antara' ],
            '251' => ['mark_id' => 24, 'title' => 'Astra' ],
            '252' => ['mark_id' => 24, 'title' => 'Combo Tour' ],
            '253' => ['mark_id' => 24, 'title' => 'Corsa' ],
            '254' => ['mark_id' => 24, 'title' => 'Frontera' ],
            '255' => ['mark_id' => 24, 'title' => 'Insignia' ],
            '256' => ['mark_id' => 24, 'title' => 'Meriva' ],
            '257' => ['mark_id' => 24, 'title' => 'Mokka' ],
            '258' => ['mark_id' => 24, 'title' => 'Omega' ],
            '259' => ['mark_id' => 24, 'title' => 'Signum' ],
            '260' => ['mark_id' => 24, 'title' => 'Vectra' ],
            '261' => ['mark_id' => 24, 'title' => 'Vivaro' ],
            '262' => ['mark_id' => 24, 'title' => 'Zafira' ],
            '263' => ['mark_id' => 24, 'title' => 'Zafira Tourier' ],

            '264' => ['mark_id' => 25, 'title' => '1007' ],
            '265' => ['mark_id' => 25, 'title' => '107' ],
            '266' => ['mark_id' => 25, 'title' => '206' ],
            '267' => ['mark_id' => 25, 'title' => '207' ],
            '268' => ['mark_id' => 25, 'title' => '3008' ],
            '269' => ['mark_id' => 25, 'title' => '307' ],
            '270' => ['mark_id' => 25, 'title' => '308' ],
            '271' => ['mark_id' => 25, 'title' => '4007' ],
            '272' => ['mark_id' => 25, 'title' => '4008' ],
            '273' => ['mark_id' => 25, 'title' => '406' ],
            '274' => ['mark_id' => 25, 'title' => '407' ],
            '275' => ['mark_id' => 25, 'title' => '508' ],
            '276' => ['mark_id' => 25, 'title' => '607' ],
            '277' => ['mark_id' => 25, 'title' => '807' ],
            '278' => ['mark_id' => 25, 'title' => 'Boxer' ],
            '279' => ['mark_id' => 25, 'title' => 'Partner' ],
            '280' => ['mark_id' => 25, 'title' => 'RCZ Sport' ],

            '281' => ['mark_id' => 26, 'title' => '911' ],
            '282' => ['mark_id' => 26, 'title' => 'Boxster' ],
            '283' => ['mark_id' => 26, 'title' => 'Cayenne' ],
            '284' => ['mark_id' => 26, 'title' => 'Cayman' ],
            '285' => ['mark_id' => 26, 'title' => 'Panamera' ],

            '286' => ['mark_id' => 27, 'title' => 'Avantime' ],
            '287' => ['mark_id' => 27, 'title' => 'Clio' ],
            '288' => ['mark_id' => 27, 'title' => 'Duster' ],
            '289' => ['mark_id' => 27, 'title' => 'Espace' ],
            '290' => ['mark_id' => 27, 'title' => 'Fluence' ],
            '291' => ['mark_id' => 27, 'title' => 'Kangoo' ],
            '292' => ['mark_id' => 27, 'title' => 'Kangoo Compact' ],
            '293' => ['mark_id' => 27, 'title' => 'Koleos' ],
            '294' => ['mark_id' => 27, 'title' => 'Laguna' ],
            '295' => ['mark_id' => 27, 'title' => 'Latitude' ],
            '296' => ['mark_id' => 27, 'title' => 'Logan' ],
            '297' => ['mark_id' => 27, 'title' => 'Master' ],
            '298' => ['mark_id' => 27, 'title' => 'Megane' ],
            '299' => ['mark_id' => 27, 'title' => 'Modus' ],
            '300' => ['mark_id' => 27, 'title' => 'Sandero' ],
            '301' => ['mark_id' => 27, 'title' => 'Sandero Stepway' ],
            '302' => ['mark_id' => 27, 'title' => 'Scenic' ],
            '303' => ['mark_id' => 27, 'title' => 'Symbol' ],
            '304' => ['mark_id' => 27, 'title' => 'Trafic' ],
            '305' => ['mark_id' => 27, 'title' => 'Twingo' ],
            '306' => ['mark_id' => 27, 'title' => 'Vel Satis' ],
            '307' => ['mark_id' => 28, 'title' => 'Fabia' ],

            '308' => ['mark_id' => 28, 'title' => 'Felicia' ],
            '309' => ['mark_id' => 28, 'title' => 'Octavia' ],
            '310' => ['mark_id' => 28, 'title' => 'Octavia Scout' ],
            '311' => ['mark_id' => 28, 'title' => 'Octavia Tour' ],
            '312' => ['mark_id' => 28, 'title' => 'Praktik' ],
            '313' => ['mark_id' => 28, 'title' => 'Roomster' ],
            '314' => ['mark_id' => 28, 'title' => 'Superb' ],
            '315' => ['mark_id' => 28, 'title' => 'Yeti' ],

            '316' => ['mark_id' => 29, 'title' => '7-series' ],
            '317' => ['mark_id' => 29, 'title' => 'Baja' ],
            '318' => ['mark_id' => 29, 'title' => 'Forester' ],
            '319' => ['mark_id' => 29, 'title' => 'Impreza' ],
            '320' => ['mark_id' => 29, 'title' => 'Justy' ],
            '321' => ['mark_id' => 29, 'title' => 'Legacy' ],
            '322' => ['mark_id' => 29, 'title' => 'Outback' ],
            '323' => ['mark_id' => 29, 'title' => 'Traviq' ],
            '324' => ['mark_id' => 29, 'title' => 'Tribeca' ],
            '325' => ['mark_id' => 29, 'title' => 'XV' ],

            '326' => ['mark_id' => 30, 'title' => 'Alphard' ],
            '327' => ['mark_id' => 30, 'title' => 'Auris' ],
            '328' => ['mark_id' => 30, 'title' => 'Avalon' ],
            '329' => ['mark_id' => 30, 'title' => 'Avensis' ],
            '330' => ['mark_id' => 30, 'title' => 'Avensis Verso' ],
            '331' => ['mark_id' => 30, 'title' => 'Aygo' ],
            '332' => ['mark_id' => 30, 'title' => 'Camry' ],
            '333' => ['mark_id' => 30, 'title' => 'Celica' ],
            '334' => ['mark_id' => 30, 'title' => 'Corolla' ],
            '335' => ['mark_id' => 30, 'title' => 'Corolla Verso' ],
            '336' => ['mark_id' => 30, 'title' => 'FJ Cruiser' ],
            '337' => ['mark_id' => 30, 'title' => 'Fortuner' ],
            '338' => ['mark_id' => 30, 'title' => 'Highlander' ],
            '339' => ['mark_id' => 30, 'title' => 'Hilux' ],
            '340' => ['mark_id' => 30, 'title' => 'IQ' ],
            '341' => ['mark_id' => 30, 'title' => 'Land Cruiser 100 GX' ],
            '342' => ['mark_id' => 30, 'title' => 'Land Cruiser 100 VX' ],
            '343' => ['mark_id' => 30, 'title' => 'Land Cruiser 200' ],
            '344' => ['mark_id' => 30, 'title' => 'Land Cruiser 80' ],
            '345' => ['mark_id' => 30, 'title' => 'Land Cruiser 90' ],
            '346' => ['mark_id' => 30, 'title' => 'Land Cruiser Prado' ],
            '347' => ['mark_id' => 30, 'title' => 'Matrix' ],
            '348' => ['mark_id' => 30, 'title' => 'MR2' ],

            '349' => ['mark_id' => 31, 'title' => '8-series' ],
            '350' => ['mark_id' => 31, 'title' => 'Amarok' ],
            '351' => ['mark_id' => 31, 'title' => 'Beetle (A4)' ],
            '352' => ['mark_id' => 31, 'title' => 'Beetle (A5)' ],
            '353' => ['mark_id' => 31, 'title' => 'Bora' ],
            '354' => ['mark_id' => 31, 'title' => 'Caddy' ],
            '355' => ['mark_id' => 31, 'title' => 'Crafter' ],
            '356' => ['mark_id' => 31, 'title' => 'CrossGolf' ],
            '357' => ['mark_id' => 31, 'title' => 'CrossPolo' ],
            '358' => ['mark_id' => 31, 'title' => 'CrossTouran' ],
            '359' => ['mark_id' => 31, 'title' => 'Eos' ],
            '360' => ['mark_id' => 31, 'title' => 'Fox' ],
            '361' => ['mark_id' => 31, 'title' => 'Golf' ],
            '362' => ['mark_id' => 31, 'title' => 'Jetta' ],
            '363' => ['mark_id' => 31, 'title' => 'Lupo' ],
            '364' => ['mark_id' => 31, 'title' => 'Multivan' ],
            '365' => ['mark_id' => 31, 'title' => 'Passat' ],
            '366' => ['mark_id' => 31, 'title' => 'Pointer' ],
            '367' => ['mark_id' => 31, 'title' => 'Polo' ],
            '368' => ['mark_id' => 31, 'title' => 'Polo Sedan' ],

            '369' => ['mark_id' => 32, 'title' => 'C30' ],
            '370' => ['mark_id' => 32, 'title' => 'C70 Convertible' ],
            '371' => ['mark_id' => 32, 'title' => 'C70 Coupe' ],
            '372' => ['mark_id' => 32, 'title' => 'S40' ],
            '373' => ['mark_id' => 32, 'title' => 'S60' ],
            '374' => ['mark_id' => 32, 'title' => 'S70' ],
            '375' => ['mark_id' => 32, 'title' => 'S80' ],
            '376' => ['mark_id' => 32, 'title' => 'S90' ],
            '377' => ['mark_id' => 32, 'title' => 'V40' ],
            '378' => ['mark_id' => 32, 'title' => 'V50' ],
            '379' => ['mark_id' => 32, 'title' => 'V70' ],
            '380' => ['mark_id' => 32, 'title' => 'V90' ],
            '381' => ['mark_id' => 32, 'title' => 'XC60' ],
            '382' => ['mark_id' => 32, 'title' => 'XC70' ],
            '383' => ['mark_id' => 32, 'title' => 'XC90' ],
        ];

        foreach ($models as $id => $data) {
            CarModel::create([
                'id' => $id,
                'mark_id' => $data['mark_id'],
                'title' => $data['title'],
            ]);
        }



    }
}